# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2023-2025 Anna <cyber@sysrq.in>

kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: fedorapython/fedora-python-tox:latest
