# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2024 Anna <cyber@sysrq.in>

version = 1
SPDX-PackageName = "repology-client"
SPDX-PackageSupplier = "Anna <cyber@sysrq.in>"
SPDX-PackageDownloadLocation = "https://repology-client.sysrq.in/"

[[annotations]]
path = "tests/cassettes/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Repology"
SPDX-License-Identifier = "CC0-1.0"
